---
title: 'Vuelos'
output: html_notebook
---

```{r}
library(tidyverse)
library(nycflights13)
head(flights)
```

```{r}
#nuevo objeto daily
# group_by destination and day
# contamos el número de vuelos en cada uno de esos días
daily <- flights %>%
  group_by(dest,day) %>%
  summarize(count = n())
daily
```


```{r}
g <- ggplot(daily, aes(x = day, y = count, color = dest)) 
g + geom_point()

```


```{r fig.height = 6.5, fig.width=6 }
#length(unique(flights$dest)) = 105

g <- ggplot(daily, aes(x = day, y = count, color = dest, shape = dest))

g + geom_point() + 
  scale_shape_manual(values = rep(0:11,9))  + 
  scale_x_continuous(breaks = 5*(0:6)) + 
  scale_y_continuous(trans = 'log2',  breaks =2^(0:9)) + 
  guides(shape = guide_legend(ncol=2,byrow=TRUE)) + 
  theme(legend.text = element_text(size=7),  legend.key.height= unit(0.2, 'cm'),legend.key.width = unit(0.1,'cm'), legend.spacing.y = unit(0.01,'cm')) + 
  labs(title = 'Flights',x = 'day', y = 'number of flights',shape = 'destination', color ='destination') 

```


```{r fig.height = 6.5, fig.width=6 }
g <- ggplot(daily, aes(x = day, y = count, color = dest))


g + geom_line() +  
  scale_x_continuous(breaks = 5*(0:6)) + 
  scale_y_continuous(trans = 'log2',  breaks =2^(0:9)) + 
  guides(color = guide_legend(ncol=2,byrow=TRUE)) + 
  theme(legend.text = element_text(size=7),  legend.key.height= unit(0.2, 'cm'),legend.key.width = unit(0.2,'cm'), legend.spacing.y = unit(0.01,'cm')) + 
  labs(title = 'Flights',x = 'day', y = 'number of flights', color ='destination') 


```


```{r fig.height = 6.5, fig.width=6.5 }


library(ggrepel)

lista <- daily %>% 
  group_by(dest) %>% 
  sample_n(1)
g <- ggplot(daily, aes(x = day, y = count, color = dest, shape = dest))


g + geom_point() + 
  geom_line() +
  geom_text_repel(data = lista, aes(label = dest),color = 'black', size = 2.5)+ 
  scale_shape_manual(values = rep(21:25,21))  + 
  scale_x_continuous(breaks = 5*(0:6)) + 
  scale_y_continuous(trans = 'log2',  breaks =2^(0:9)) + 
  guides(shape = guide_legend(ncol=2,byrow=TRUE)) + 
  theme(legend.text = element_text(size=7),  legend.key.height= unit(0.2, 'cm'), legend.key.width = unit(0.1,'cm'), legend.spacing.y = unit(0.01,'cm')) + 
  labs(title = 'Flights',x = 'day', y = 'number of flights',shape = 'destination', color ='destination')


```
GAPMINDER
```{r}
gap <- read.csv("gapminder-health-income.csv")
str(gap)
```

```{r}
library(viridis)
options(scipen=10000)
p<- ggplot(gap, aes(x = income, y= health))

lista <- gap %>% 
  filter(population > 2.5e8)

g <- ggplot(daily, aes(x = day, y = count, color = dest, shape = dest))
  
p + geom_point(aes(size = population, color = population)) + 
  scale_x_log10(breaks = 10^(3:5)) +
  scale_y_log10(breaks = 5*(9:17)) +
  scale_color_viridis(option = 'D') +
  theme(legend.text = element_text(size=9),  legend.key.height= unit(1.5, 'cm'), legend.key.width = unit(0.5,'cm'))+
  geom_text(data = lista, aes(label = country),color = 'black', size = 3) +
  labs(title = 'gapminder',x = 'income', y = 'health',color= 'population x million')+
  guides(size = FALSE)


```

